/*화학과를 제외하고 학과별로 학생들의 평점 평균을 검색하세요*/
SELECT * FROM STUDENT;
SELECT ROUND(AVG(AVR),3) AS 평점평균, MAJOR FROM STUDENT
WHERE MAJOR != '화학'
GROUP BY MAJOR;

SELECT * FROM TAB;

/* 화학과를 제외한 각 학과별 평균 평점 중에 평점이 2.0 이상인 정보를 검색하세요*/

SELECT ROUND(AVG(AVR),3) AS 평점평균, MAJOR FROM STUDENT
WHERE MAJOR != '화학'
GROUP BY MAJOR
HAVING ROUND(AVG(AVR), 2) >= 2.0;

/*송강 교수가 강의하는 과목을 검색한다.*/
/*테이블 : PROFESSOR P, COURSE C*/

SELECT * FROM PROFESSOR;
SELECT * FROM COURSE;
SELECT PNO FROM PROFESSOR WHERE PNAME = '송강';

SELECT PNAME,PNO, CNO,CNAME 
FROM PROFESSOR
JOIN COURSE USING(PNO)
WHERE PNAME = '송강';

SELECT P.PNO, PNAME, CNO, CNAME
FROM PROFESSOR P, COURSE C
WHERE P.PNO = C.PNO AND PNAME= '송강';

/* 화학 관련 과목을 강의하는 교수의 명단을 검색한다*/
SELECT PNAME, PNO,SECTION, CNAME
FROM professor
JOIN COURSE USING (PNO)
WHERE SECTION LIKE '%화학%';

/* 화학과 1학년 학생의 기말고사 성적을 검색한다*/
/* STUDENT SCORE COURSE */
SELECT * FROM STUDENT;
SELECT * FROM SCORE;
SELECT * FROM COURSE;

SELECT ST.SNO, SNAME, MAJOR, SYEAR, SC.CNO, CNAME, RESULT
FROM STUDENT ST, SCORE SC, COURSE CO
WHERE ST.SNO = SC.SNO AND SC.CNO = CO.CNO AND MAJOR='화학' AND SYEAR=1;

SELECT SNO, SNAME, MAJOR, SYEAR, CNO, CNAME, RESULT
FROM STUDENT
JOIN SCORE USING(SNO)
JOIN COURSE USING(CNO)
WHERE MAJOR = '화학' AND SYEAR=1;

/* 화학과 1학년 학생이 수강하는 과목을 검색한다*/
/* 화학과 1학년 학생의 일반화학 기말고사 점수를 검색한다*/
SELECT ST.SNO, SNAME, MAJOR, SYEAR, SC.CNO, CNAME, RESULT
FROM STUDENT ST, SCORE SC, COURSE CO
WHERE ST.SNO = SC.SNO AND SC.CNO = CO.CNO AND MAJOR='화학' AND CNAME='일반화학' AND SYEAR=1;

SELECT SNO, SNAME, MAJOR, SYEAR, CNO, CNAME, RESULT
FROM STUDENT
JOIN SCORE USING(SNO)
JOIN COURSE USING(CNO)
WHERE MAJOR='화학' AND CNAME='일반화학' AND SYEAR=1;