SELECT * FROM EMPLOYEES;
SELECT * FROM EMPLOYEES_ROLE;

/*employees와 employees_role에서 레코드의 사원명단을 구하시오*/

SELECT LAST_NAME, JOB_ID, DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID = 10
UNION
SELECT LAST_NAME, JOB_ID, DEPARTMENT_ID FROM EMPLOYEES_ROLE
WHERE JOB_ID ='IT PROG'